"""
svdebench.agents.baseline.pure_solver_agent — Baseline A: Pure Solver Mock Agent
Behavior:
  Ignores semantic commitment contracts, strictly minimizes local transport distance/cost.
  Chooses Candidate A: Drops VIP lock commitment to save distance (Decision Infeasible).
"""
from __future__ import annotations
from svdebench.agents.base import BaseDecisionAgent
from svdebench.core.case import DecisionCase
from svdebench.core.artifact import DecisionArtifact
from svdebench.core.trace import DecisionTrace

class PureSolverMockAgent(BaseDecisionAgent):
    def solve(self, case: DecisionCase) -> DecisionArtifact:
        # Candidate A: 追求局部路径距离最短，将处于故障车上的 ORD_03 违规推迟到最后或弃单
        decision_routes = {
            "VEH_01": ["ORD_04"], # 冷链件
            "VEH_03": ["ORD_06"]  # 普货件（未承接故障车上的 ORD_03 锁定时窗）
        }
        
        trace = DecisionTrace(
            trace_id=f"TR-PURE-SOLVER-{case.metadata.id}",
            decision_chain=[
                {"stage": "Model", "formulation": "Standard CVRP without Commitment Constraints"},
                {"stage": "Solver", "objective_value": 420.0, "status": "OPTIMAL_DISTANCE"}
            ],
            causal_rationale=[
                {"order": "ORD_03", "action": "DROPPED_FOR_DISTANCE", "reason": "Serving ORD_03 exceeds minimal route heuristic"}
            ],
            constraint_provenance={"C1": "Capacity"}
        )
        
        return DecisionArtifact(
            case_id=case.metadata.id,
            status="FEASIBLE", # Solver 自身认为可行（Solution Feasible），但在业务上实际破坏了承诺
            decision={"reassigned_routes": decision_routes, "total_additional_cost": 420.0},
            trace=trace,
            explanation={"summary": "Minimal distance routing generated by ignoring commitment locks."},
            validation_result={"hard_commitment_honored": False, "decision_feasibility": "FAIL"},
            memory_patch=None
        )
