"""Planning Input/Output Contracts — Phase 0 of SVDE Integration Specification.

Defines the formal contracts across the decision pipeline:
- PlanningIntent: business intent requesting planning capabilities
- CandidatePlan: output generated by OR solver engine
- DecisionArtifact: verified, immutable decision ready for execution
- PlanAuditReport: multi-dimensional independent audit result (Physical/Business/Semantic)
"""
from dataclasses import dataclass, field
from enum import Enum
from typing import Dict, List, Optional, Tuple, Any
import datetime


class PlanningCapabilityType(str, Enum):
    TERRITORY_ALIGNMENT = "TERRITORY_ALIGNMENT"         # 辖区划片
    PERIODIC_VISIT_PLANNING = "PERIODIC_VISIT_PLANNING" # 周期排班 (4周20天严格同周几)
    DAILY_ROUTE_OPTIMIZATION = "DAILY_ROUTE_OPTIMIZATION" # 单日路线 (崇川中心闭环TSP)


class AuditDimension(str, Enum):
    PHYSICAL_FEASIBILITY = "PHYSICAL_FEASIBILITY"       # 物理可行性: 速度、距离、路网、容量
    BUSINESS_COMPLIANCE = "BUSINESS_COMPLIANCE"         # 业务合规性: 频次、同周几、大店零脱访
    SEMANTIC_PURITY = "SEMANTIC_PURITY"                 # 语义纯洁性: 零算法泄漏、对象边界规范


@dataclass(frozen=True)
class PlanningIntent:
    intent_id: str
    capability_type: PlanningCapabilityType
    target_rep_id: str
    target_horizon_label: str                           # 如 "2026-06"
    working_days: tuple                                 # ("2026-06-01", ..., "2026-06-26")
    max_daily_stops: int = 6
    max_daily_workload_min: float = 480.0
    same_weekday_required: bool = True                  # 1A 严格同周几硬规则


@dataclass(frozen=True)
class PlannedStop:
    stop_idx: int
    store_code: str
    store_name: str
    district: str
    planned_service_min: float = 50.0
    leg_distance_from_prev_km: float = 0.0
    leg_transit_from_prev_min: float = 0.0


@dataclass(frozen=True)
class PlannedDailyRoute:
    date_str: str
    weekday_name: str                                   # 周一 / 周二 等
    rep_id: str
    stops: List[PlannedStop] = field(default_factory=list)
    depot_outbound_transit_min: float = 0.0
    depot_inbound_transit_min: float = 0.0
    total_daily_distance_km: float = 0.0
    total_daily_transit_min: float = 0.0
    total_daily_service_min: float = 0.0
    total_daily_workload_min: float = 0.0

    @property
    def stops_count(self) -> int:
        return len(self.stops)


@dataclass(frozen=True)
class CandidatePlan:
    plan_id: str
    intent_id: str
    rep_id: str
    period_label: str
    daily_routes: List[PlannedDailyRoute] = field(default_factory=list)
    solver_name: str = "CP-SAT + Held-Karp Exact"
    solver_status: str = "OPTIMAL"
    total_scheduled_visits: int = 0
    total_monthly_transit_min: float = 0.0
    total_monthly_distance_km: float = 0.0


@dataclass(frozen=True)
class DimensionAuditResult:
    dimension: AuditDimension
    is_passed: bool
    violations_count: int
    violation_details: List[str] = field(default_factory=list)


@dataclass(frozen=True)
class PlanAuditReport:
    plan_id: str
    is_fully_compliant: bool
    cadence_compliance_rate: float                      # 0.0 ~ 100.0%
    dimension_results: Dict[AuditDimension, DimensionAuditResult] = field(default_factory=dict)
    summary_message: str = ""


@dataclass(frozen=True)
class DecisionArtifact:
    """Immutable, production-ready decision output passed to SFA/CRM execution."""
    artifact_id: str
    candidate_plan_ref: str
    audit_report_ref: str
    approved_by: str
    approved_at: datetime.datetime
    published_schedule: Dict[str, List[str]]            # date_str -> [store_codes in sequence]
    status: str = "APPROVED_FOR_EXECUTION"
